name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:   # 入力パラメータ名
             type: string
             default: Hello
             required: true
             description: A cheerful word
            log-level:
                type: choice
                options:
                    - info
                    - warn
                    - error
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ vars.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "${{inputs.greeting}}"
            - run: echo "${USERNAME}"
            - run: echo "${PASSWORD}"
            - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"